services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: hyperformant-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hyperformant-dev
      POSTGRES_DB: hyperformant
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: hyperformant-n8n
    ports:
      - '5678:5678'
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_ENCRYPTION_KEY=hyperformant-n8n-encryption-key
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=hyperformant
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=hyperformant-dev
      - DB_POSTGRESDB_SCHEMA=n8n
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
    volumes:
      - n8n-data:/home/node/.n8n
      - ./n8n/workflows:/home/node/workflows
    depends_on:
      postgres:
        condition: service_healthy

  # Email Testing (Development Only)
  inbucket:
    image: inbucket/inbucket:stable
    container_name: hyperformant-inbucket
    ports:
      - '9000:9000' # Web UI
      - '2500:2500' # SMTP
      - '1100:1100' # POP3

volumes:
  postgres-data:
  n8n-data:
